mail_username: <%= ENV.fetch("MAIL_USERNAME") %>
mail_password: <%= ENV.fetch("MAIL_PASSWORD") %>

production:
  mail_username: <%= ENV.fetch("MAIL_USERNAME") %>
  mail_password: <%= ENV.fetch("MAIL_PASSWORD") %>
